// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from MsgType.proto</summary>
  public static partial class MsgTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Nc2dUeXBlLnByb3RvEgVQcm90byoxCgdNc2dUeXBlEhEKDWVuVGVzdFJl",
            "cXVlc3QQABITCg9lblRlc3RSZXNwb25zZXMQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.MsgType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgType {
    [pbr::OriginalName("enTestRequest")] EnTestRequest = 0,
    [pbr::OriginalName("enTestResponses")] EnTestResponses = 1,
  }

  #endregion

}

#endregion Designer generated code
