// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from ProtoEnum.proto</summary>
  public static partial class ProtoEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0VudW0ucHJvdG8SBVByb3RvKksKB01zZ1R5cGUSEQoNZW5UZXN0",
            "UmVxdWVzdBAAEhMKD2VuVGVzdFJlc3BvbnNlcxABEhgKFGVuTGlua1N1Y2Nl",
            "c1Jlc3BvbnNlEGQqGgoJRXJyb3JDb2RlEg0KCUVycm9yTm9uZRAAYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.MsgType), typeof(global::Proto.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MsgType {
    [pbr::OriginalName("enTestRequest")] EnTestRequest = 0,
    [pbr::OriginalName("enTestResponses")] EnTestResponses = 1,
    /// <summary>
    ///客户端链接成功
    /// </summary>
    [pbr::OriginalName("enLinkSuccesResponse")] EnLinkSuccesResponse = 100,
  }

  public enum ErrorCode {
    [pbr::OriginalName("ErrorNone")] ErrorNone = 0,
  }

  #endregion

}

#endregion Designer generated code
